### ISSUE TITLE
请问下作者，字向量怎么训练出来的？

### ISSUE THREAD

**Issue by aoleiming** [scruel/campusQA#1]
RT

**Comment by scruel** [comment]
你好，我这里因为数据量不大，没有分词（容易有未登录词)，是直接用统计单字然后生成的词典。
比如 我爱中华 生成的词典就是 0 我 1 中 2 华 3
字向量就是[1, 1, 1, 1]
总之是比较简单的应用，数据量大的话就可能不能这样玩了。

**Comment by aoleiming** [comment]
了解了，谢谢！
可以加您QQ请教问题吗？
我的QQ是176827885

**Comment by scruel** [comment]
@aoleiming 已加
